<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AddRewardProviders.aspx.cs" Inherits="AddRewardProviders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <!--modal style-->
              <style type="text/css">
                .modal {
                      max-height: 90%;
                    }

                    .modal-form-row {
                      margin-bottom: 0px;
                    }
              </style>

<div style ="position: relative; top: 60px;">

        <div style = "float: left; width: 15%;">
        <ul id="slide-out" class="side-nav fixed" style = "width:15%;">
            <li><div class="user-view">
                <asp:Image ID ="profilePicture" Height ="120px" Width ="120px" CssClass ="circle user" runat ="server"/>
                <asp:Label ID="lblUser" runat="server" Text="" CssClass ="user1"></asp:Label>
                <h5 class="user1">Admin</h5>
                <asp:Label ID="lblBalance" runat="server" CssClass ="user1"></asp:Label>
            </div></li>
            <li><a href ="/UserOptions.aspx">User Options</a></li>
            <li><a href="/ViewRewards.aspx">View Rewards</a></li>
            <li><a href ="/AddRewardProviders.aspx">View Reward Providers</a></li>
            <li><a href="AnalyticsPage.aspx">View Analytics</a></li>
            <li><a href="/ManageCommunityPost.aspx">Community Events</a></li>
            <li><a href="/Default.aspx">Logout</a></li>
        </ul>
    </div>


    <div style ="float: right; width: 85%;">
        <div style = "margin-left:auto; margin-right:auto; width:85%;">
        <nav class="feednav" >
            <div class="nav-wrapper">
                <a class="brand-logo nav1 panel">Reward Provider Dashboard</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down"> 
                    <li><asp:Button runat="server" ID="btnAddProvider" Text="Add Provider" CssClass="nav1 modal-trigger" data-target="modal2" OnClick="btnAddProvider_Click"/></li>
                </ul>
            </div>
        </nav>
        <div style ="background-color: white;">
            <asp:GridView ID="grdProviders" ValidationGroup="validNewProvider" AutoGenerateColumns="False" runat="server"  class="striped"
                         OnRowCancelingEdit="grdProviders_RowCancelingEdit" OnRowEditing="grdProviders_RowEditing" OnRowUpdating="grdProviders_RowUpdating" DataKeyNames="ProviderID" ShowHeaderWhenEmpty="True" OnRowDeleting="grdProviders_RowDeleting" AutoGenerateDeleteButton="True" OnRowCommand="grdProviders_RowCommand">
                        <Columns>                            
                            <asp:CommandField ShowEditButton="true" CausesValidation="true" ValidationGroup="validNewProvider"/>
                            <asp:TemplateField HeaderText="Provider ID">
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderID" runat="server" Text='<%# Eval("ProviderID") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Name">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtgvProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="reqgvProviderName" ControlToValidate="txtgvProviderName" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewProvider"></asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtgvProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>' TextMode="SingleLine"></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="reqgvProviderEmail" ControlToValidate="txtgvProviderEmail" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewProvider"></asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Pending Review">
                                <ItemTemplate>
                                    <asp:Label ID="lblPendingReview" runat="server" Text='<%# Eval("PendingReview") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="View Application">
                                <ItemTemplate>
                                    <asp:Button ID="btnViewApp" runat="server" Text="View Application" CommandName="ViewApp" />
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Pay Provider">
                                <ItemTemplate>
                                    <asp:Button ID="btnPay" runat="server" OnClick="btnPay_Click" Text="Pay Provider" CssClass="nav1 modal-trigger" data-target="modal3" />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <asp:Label ID="lvlgvNoProvider" runat="server" Text="No Records Found"></asp:Label>
                        </EmptyDataTemplate>
                </asp:GridView>
            </div>

        </div>
    </div>
</div>

<div id="modal2" class="modal">
    <div class="modal-content">
        <h4>Create Event</h4>
          <!-- Drop Down Menu-->
        <form action="#">
            <div class="file-field input-field">
                <div class="btn">
                <span>Upload Photo</span>
                <input type="file">
                </div>
                <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
                </div>
            </div>
        </form>

        <div class="row">
            <form class="col s12">
                <div class="row modal-form-row">
                    <div class="input-field col s12">
                    <input id="image_url" type="text" class="validate" value="Rocktown Beer Fest Tickets">
                    <label for="image_url">Reward Title</label>
                </div>
                </div>            
            </form>
        </div>

        <div class="input-field col s12">
            <select>
            <option value=""> $10</option>
            <option value="2">$25</option>
            <option value="3">$50</option>
            </select>
            <label>Price</label>
        </div>

        <div class="row">
            <form class="col s12">
                <div class="row modal-form-row">
                    <div class="input-field col s12">
                    <input id="image_url" type="text" class="validate" value="10">

                    <label for="image_url">Quantity</label>
                </div>
                </div>            
            </form>
        </div>

        <div class="row">
            <form class="col s12">
                <div class="row modal-form-row">
                    <div class="input-field col s12">
                    <asp:TextBox ID="image_url" CssClass="validate" runat="server"></asp:TextBox>
                    <label for="image_url">Description</label>
                </div>
                </div>            
            </form>
        </div>

        <div class="modal-footer">
            <a class=" modal-action modal-close waves-effect waves-green btn-flat">Add</a>
        </div>

    </div>
</div>
    
<div id="modal3" class="modal">
    <div class="modal-content">
        <h4>Create Event</h4>
          <!-- Drop Down Menu-->
        <form action="#">
            <div class="file-field input-field">
                <div class="btn">
                <span>Upload Photo</span>
                <input type="file">
                </div>
                <div class="file-path-wrapper">
                <input class="file-path validate" type="text">
                </div>
            </div>
        </form>

        <div class="row">
            <form class="col s12">
                <div class="row modal-form-row">
                    <div class="input-field col s12">
                    <input id="image_url" type="text" class="validate" value="Rocktown Beer Fest Tickets">
                    <label for="image_url">Reward Title</label>
                </div>
                </div>            
            </form>
        </div>

        <div class="input-field col s12">
            <select>
            <option value=""> $10</option>
            <option value="2">$25</option>
            <option value="3">$50</option>
            </select>
            <label>Price</label>
        </div>

        <div class="row">
            <form class="col s12">
                <div class="row modal-form-row">
                    <div class="input-field col s12">
                    <input id="image_url" type="text" class="validate" value="10">
                    <label for="image_url">Quantity</label>
                </div>
                </div>            
            </form>
        </div>

        <div class="row">
            <form class="col s12">
                <div class="row modal-form-row">
                    <div class="input-field col s12">
                    <input id="image_url" type="text" class="validate">
                    <label for="image_url">Description</label>
                </div>
                </div>            
            </form>
        </div>

        <div class="modal-footer">
            <a class=" modal-action modal-close waves-effect waves-green btn-flat">Add</a>
        </div>

    </div>
</div>        

    <script type="text/javascript">

              function OpenPopup(ctrlid)

              {

                  window.open("L2List.aspx?ctrlid=" + ctrlid,"List","left = 300, top=150,scrollbars=no,resizable=no,width=400,height=280");

                  return false;

              }

</script>

    <!-- Add modular-->

<script type="text/javascript">
    $(document).ready(function () {
        $('select').material_select();
    });

</script>
      <script type="text/javascript">
          $(document).ready(function () {
              // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
              $('.modal-trigger').leanModal();
          });
      </script>
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>

      <!-- MODAL ADDED-->




    
<%--<center>
    <h1 class="display-4">Reward Provider Options</h1>
    <div class="jumbotron agent-1" style="width:78%; background-color:lightblue; opacity:0.88; border-radius:25px; padding-top:1px;">
        <div style="float:left;">
            <asp:Button ID="btnAddProvider" CssClass="btn btn-primary" runat="server" OnClick="btnAddProvider_Click1" Text="Add Reward Provider" CausesValidation="False" />
            <asp:Button ID="btnClear" CssClass="btn btn-secondary" runat="server" Text="Clear" CausesValidation="False" OnClick="btnClear_Click1" />
            <asp:Button ID="AutoFillRewardProviderID" CssClass="btn btn-secondary" runat="server" OnClick="AutoFillRewardProviderID_Click" CausesValidation="false" Text="AutoFillRewardProvider"  />
        </div>
        <br />
        <br />
        <asp:Panel ID="providerPanel" runat="server" Visible="false">
            <div>
                <div class="form-group">
                    <asp:TextBox ID="txtNewProviderName" placeholder="Provider Name" runat="server"  ></asp:TextBox>
                    <asp:RequiredFieldValidator ID="reqProviderName"  ControlToValidate="txtNewProviderName" Text="(Required)" Font-Bold="true" ForeColor="Red" runat="server"></asp:RequiredFieldValidator>
                </div>
                <div class="form-group">
                    <asp:TextBox ID="txtNewProviderEmail" placeholder="Provider Email" runat="server"  TextMode="Email"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="reqProviderEmail" ControlToValidate="txtNewProviderEmail" Text="(Required)" Font-Bold="true" ForeColor="Red" runat="server"></asp:RequiredFieldValidator>
                </div>
                <div>
                    <asp:Button ID="btnAdd" CssClass="btn btn-primary" runat="server" OnClick="btnAdd_Click1" Text="Add"  />
                </div>
            </div>
        </asp:Panel>
        <br />
        <br />
        <asp:TextBox ID="txtSearch"  placeholder="Search" runat="server"></asp:TextBox>
        <asp:Button ID="btnSearch" CssClass="btn btn-primary" runat="server" Text="Search" OnClick="btnSearch_Click" CausesValidation="False" />
        <br />
        <br />

        <asp:Label ID="lblResult" runat="server"></asp:Label>

        <div id="RewardProviderGrid">
        <%--<asp:GridView ID="grdProviders" ValidationGroup="validNewProvider" AutoGenerateColumns="False" runat="server" style="left: 311px; top: 799px" Width="545px" 
                         OnRowCancelingEdit="grdProviders_RowCancelingEdit" OnRowEditing="grdProviders_RowEditing" OnRowUpdating="grdProviders_RowUpdating" DataKeyNames="ProviderID" ShowHeaderWhenEmpty="True" OnRowDeleting="grdProviders_RowDeleting" AutoGenerateDeleteButton="True" OnRowCommand="grdProviders_RowCommand">
                        <Columns>                            
                            <asp:CommandField ShowEditButton="true" CausesValidation="true" ValidationGroup="validNewProvider"/>
                            <asp:TemplateField HeaderText="Provider ID">
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderID" runat="server" Text='<%# Eval("ProviderID") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Name">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtgvProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="reqgvProviderName" ControlToValidate="txtgvProviderName" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewProvider"></asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderName" runat="server" Text='<%# Eval("ProviderName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Provider Email">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txtgvProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>' TextMode="SingleLine"></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="reqgvProviderEmail" ControlToValidate="txtgvProviderEmail" Text="(Required)" Display="Dynamic" Runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="validNewProvider"></asp:RequiredFieldValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblgvProviderEmail" runat="server" Text='<%# Eval("ProviderEmail") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Pending Review">
                                <ItemTemplate>
                                    <asp:Label ID="lblPendingReview" runat="server" Text='<%# Eval("PendingReview") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="View Application">
                                <ItemTemplate>
                                    <asp:Button ID="btnViewApp" runat="server" Text="View Application" CommandName="ViewApp" />
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <asp:Label ID="lvlgvNoProvider" runat="server" Text="No Records Found"></asp:Label>
                        </EmptyDataTemplate>
                        </asp:GridView>--%>    <%--</div>
        <asp:Panel ID="appPanel" runat="server" Visible="false">
            <table style="background-color: antiquewhite">
                <tr>
                    <td>
                        <asp:Label ID="lblCompanyName" runat="server" Text="Company Name"></asp:Label>
                        <asp:TextBox ID="txtCompanyName" runat="server"></asp:TextBox>
                    </td>
                    <td>
                        <asp:Label ID="lblEmail" runat="server" Text="Company Email"></asp:Label>
                        <asp:TextBox ID="txtEmail" runat="server"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label ID="lblDesc" runat="server" Text="Why do you want to be a part of Motiv8?"></asp:Label>
                        <asp:TextBox ID="txtDesc" runat="server" TextMode="MultiLine" Height="113px" Width="315px"></asp:TextBox>
                    </td>
                    <td>
                        
                    </td>
                </tr>
            </table>
        </asp:Panel>
    </div>
</center>--%>
    
    
                
                
                    
                
        
    

    
</asp:Content>

